name: Deploy extensions
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    name: Deploy
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install npm dependencies
        run: npm install
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.1"
      - name: Install Bundler
        run: gem install bundler
      - name: Deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          # .env content after a deploy
          SHOPIFY_API_KEY: eecce11abe993abac8e532b6a5f0acf9
        run: npm run deploy -- -f
